
package com.cuit.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://webservice.cuit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://webservice.cuit.com/", className = "com.cuit.client.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://webservice.cuit.com/", className = "com.cuit.client.GetValueResponse")
    @Action(input = "http://webservice.cuit.com/Server/getValueRequest", output = "http://webservice.cuit.com/Server/getValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reverseString", targetNamespace = "http://webservice.cuit.com/", className = "com.cuit.client.ReverseString")
    @ResponseWrapper(localName = "reverseStringResponse", targetNamespace = "http://webservice.cuit.com/", className = "com.cuit.client.ReverseStringResponse")
    @Action(input = "http://webservice.cuit.com/Server/reverseStringRequest", output = "http://webservice.cuit.com/Server/reverseStringResponse")
    public String reverseString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
